### PR TITLE
feat: change sendHostname

### PR DESCRIPTION
**Pull request by jinwoo-kim-nhn**

### CODE REVIEW

**Comment by seonim-ryu** [comment]
Can one of the admins verify this patch?

**Comment by jinwoo-kim-nhn** [comment]
ok to test

**Comment by jungeun-cho** [comment]
[12/10] 이견없습니다.

**Comment by jinwoo-kim-nhn** [comment]
ok to test

**Comment by jinwoo-kim-nhn** [comment]
ok to test

**Comment by jinwoo-kim-nhn** [comment]
ok to test

**Comment by jinwoo-kim-nhn** [comment]
ok to test

**Pull request merged**
